server:
  port: 8080
  servlet:
    context-path: /api
spring:
  application:
    name: spring-security-demo
  datasource:
    username: root
    password: zq199613
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/login?autoReconnect=true&useUnicode=true&characterEncoding=utf-8&autoReconnect=true
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
log:
  enable: true
